import { Practicum } from './types';

export const practicums: Practicum[] = [
  {
    id: 'am-modulation',
    title: 'AM Modulation',
    titleId: 'Modulasi Amplitudo',
    moduleCode: 'TE02005',
    description: 'Investigate amplitude modulation index, waveforms, and envelope detection.',
    descriptionId: 'Menyelidiki indeks modulasi amplitudo, bentuk gelombang, dan deteksi selubung sinyal.',
    category: 'analog',
    status: 'active',
    route: '/modul/am',
    tags: ['Sumber Sinyal', 'Penguat', 'Rangkaian Penala', 'AFG', 'Osiloskop'],
    instruments: ['AFG-2025', 'GDS-1102-U', 'GFC-8010H', 'PUDAK PTE-011'],
  },
  {
    id: 'fm-modulation',
    title: 'FM Modulation',
    titleId: 'Modulasi Frekuensi',
    moduleCode: 'TE02009',
    description: 'Analyze frequency modulation principles, frequency deviation, and modulation index.',
    descriptionId: 'Menganalisis prinsip modulasi frekuensi, deviasi frekuensi, dan indeks modulasi FM.',
    category: 'analog',
    status: 'active',
    route: '/modul/fm',
    tags: ['Sumber Sinyal', 'Modulator FM', 'AFG', 'Osiloskop', 'GFC'],
    instruments: ['AFG-2025', 'GDS-1102-U', 'GFC-8010H', 'PUDAK PTE-011'],
  },
  {
    id: 'demodulation',
    title: 'AM Demodulation',
    titleId: 'Demodulasi',
    moduleCode: 'TE02007',
    description: 'Recover intelligence from amplitude modulated carrier using envelope detector circuit.',
    descriptionId: 'Mengembalikan sinyal informasi dari pembawa termodulasi AM menggunakan rangkaian detektor.',
    category: 'analog',
    status: 'active',
    route: '/modul/demodulasi',
    tags: ['Detektor', 'Sumber Sinyal', 'Penguat', 'AFG', 'Osiloskop'],
    instruments: ['AFG-2025', 'GDS-1102-U', 'PUDAK PTE-011'],
  },
  {
    id: 'digital-signals',
    title: 'Digital Signals',
    titleId: 'Sinyal Digital',
    moduleCode: 'TE03001',
    description: 'Demonstrate digital signal transmission including NRZ, telephone, and ADC/DAC conversion.',
    descriptionId: 'Memperagakan transmisi sinyal digital: NRZ, konversi ADC/DAC, dan telepon digital.',
    category: 'digital',
    status: 'active',
    route: '/modul/digital',
    tags: ['Data Source', 'Data Receiver', 'ADC/DAC', 'AFG', 'Osiloskop'],
    instruments: ['AFG-2025', 'GDS-1102-U', 'PUDAK PTE-001'],
  },
  {
    id: 'sample-and-hold',
    title: 'Sample and Hold',
    titleId: 'Sampling dan Penahanan',
    moduleCode: 'TE03005',
    description: 'Demonstrate sampling process and explain the effect of sampling frequency and pulse width.',
    descriptionId: 'Mendemonstrasikan proses S&H dan pengaruh frekuensi sampling serta lebar pulsa pencuplik.',
    category: 'digital',
    status: 'active',
    route: '/modul/sample-hold',
    tags: ['Sample Hold', 'Mux', 'Filter', 'AFG', 'Osiloskop', 'GFC'],
    instruments: ['AFG-2025', 'GDS-1102-U', 'GFC-8010H', 'PUDAK PTE-001-09'],
  },
  {
    id: 'aliasing-multiplex',
    title: 'Aliasing & Multiplex',
    titleId: 'Aliasing & Multiplexing',
    moduleCode: 'TE03006',
    description: 'Identify aliasing problems and demonstrate time-division multiplex signal transmission.',
    descriptionId: 'Mengidentifikasi aliasing dan mendemonstrasikan pengiriman dua sinyal TDM pada satu kanal.',
    category: 'digital',
    status: 'active',
    route: '/modul/aliasing',
    tags: ['Aliasing', 'TDM', 'Filter', '2× AFG', 'Osiloskop', 'GFC'],
    instruments: ['2× AFG-2025', 'GDS-1102-U', 'GFC-8010H', 'PUDAK PTE-001-09'],
  },
];