import { Practicum } from './types';

export const practicums: Practicum[] = [
  {
    id: 'am-modulation',
    title: 'AM Modulation',
    titleId: 'Modulasi AM',
    moduleCode: 'TE03002',
    description: 'Investigate amplitude modulation index, waveforms, and envelope detection.',
    descriptionId: 'Menyelidiki indeks modulasi amplitudo, bentuk gelombang, dan deteksi selubung.',
    category: 'analog',
    status: 'coming-soon',
    tags: ['Catu Daya', 'Sumber Sinyal', 'Penguat', 'Rangkaian Penala'],
  },
  {
    id: 'demodulation',
    title: 'AM Demodulation',
    titleId: 'Demodulasi AM',
    moduleCode: 'TE03003',
    description: 'Recover intelligence from amplitude modulated carrier using envelope detector circuit.',
    descriptionId: 'Mengembalikan sinyal informasi dari pembawa termodulasi amplitudo menggunakan detektor selubung.',
    category: 'analog',
    status: 'coming-soon',
    tags: ['Catu Daya', 'Sumber Sinyal', 'Penguat', 'Detektor'],
  },
  {
    id: 'fm-modulation',
    title: 'FM Modulation',
    titleId: 'Modulasi FM',
    moduleCode: 'TE03004',
    description: 'Analyze frequency modulation principles, frequency deviation, and modulation index.',
    descriptionId: 'Menganalisis prinsip modulasi frekuensi, deviasi frekuensi, dan indeks modulasi.',
    category: 'analog',
    status: 'coming-soon',
    tags: ['Catu Daya', 'Sumber Sinyal', 'Modulator FM'],
  },
  {
    id: 'digital-signals',
    title: 'Digital Signals',
    titleId: 'Sinyal Digital',
    moduleCode: 'TE03001',
    description: 'Demonstrate digital signal transmission including NRZ, telephone, and analog signals.',
    descriptionId: 'Memperagakan pengiriman sinyal digital termasuk NRZ, telepon, dan sinyal analog.',
    category: 'digital',
    status: 'coming-soon',
    tags: [],
  },
  {
    id: 'sample-and-hold',
    title: 'Sample and Hold',
    titleId: 'Sampling dan Penahanan',
    moduleCode: 'TE03005',
    description: 'Demonstrate sampling process and explain the effect of sampling frequency and pulse width.',
    descriptionId: 'Mendemonstrasikan proses sampling dan menjelaskan pengaruh frekuensi sampling serta lebar pulsa.',
    category: 'digital',
    status: 'coming-soon',
    tags: [],
  },
  {
    id: 'aliasing-multiplex',
    title: 'Aliasing & Multiplex Signaling',
    titleId: 'Aliasing dan Multiplex Signaling',
    moduleCode: 'TE03006',
    description: 'Identify aliasing problems and demonstrate time-division multiplex signal transmission.',
    descriptionId: 'Mengidentifikasi masalah aliasing dan mendemonstrasikan pengiriman dua sinyal dengan metode pencuplikan.',
    category: 'digital',
    status: 'coming-soon',
    tags: [],
  },
];
